# Generated by Django 3.2.7 on 2021-11-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('lastn_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateTimeField()),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiration_date', models.DateTimeField()),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_card_information', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration', models.DateTimeField()),
                ('cvv', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_types', models.CharField(blank=True, max_length=50, null=True)),
                ('tour_names', models.CharField(blank=True, max_length=50, null=True)),
                ('tour_short_description', models.TextField(blank=True, max_length=100, null=True)),
                ('tour_long_descript', models.TextField(blank=True, max_length=500, null=True)),
                ('tour_price', models.CharField(blank=True, max_length=50, null=True)),
                ('tour_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('duartion_start_date', models.DateTimeField()),
                ('duartion_end_date', models.DateTimeField()),
                ('tour_location', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('total_seats', models.IntegerField(blank=True, null=True)),
                ('booked_seat', models.IntegerField(blank=True, null=True)),
                ('booking_start_date', models.DateTimeField()),
                ('bookin_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, max_length=500, null=True)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.tour')),
            ],
        ),
    ]
