# Generated by Django 3.2.7 on 2021-11-15 13:37

from django.db import migrations, models
import django.utils.timezone
import user.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(blank=True, max_length=500, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='Password')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Country')),
                ('time_zone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time Zone')),
                ('time_zone_sub', models.CharField(blank=True, max_length=300, null=True, verbose_name='Time Zone2')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Last Login')),
                ('first_login', models.DateTimeField(null=True, verbose_name='First Login')),
                ('login_count', models.IntegerField(null=True, verbose_name='Login Count')),
                ('active', models.BooleanField(default=True, verbose_name='User Active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', user.manager.UserManager()),
            ],
        ),
    ]
